### ISSUE TITLE
Superusers can't view challenges page

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-University#15]
Currently, superusers can't visit the challenges page.

Steps to reproduce : 
1. Create a superuser
2. Login via the `/admin` page
3. Visit the `/challenges` page

You should get a 500 error message.

**Comment by reznok** [comment]
This will be fixed with the new admin interface.
Django superusers won't exist anymore.

This is happening because a UserProfile is not automatically generated for manually added accounts.

**Comment by reznok** [comment]
Super users are no longer a thing
