### ISSUE TITLE
View list of available titles

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-University#37]
I think it would be good for motivation if we could see the titles and descriptions!

For example, seeing the description for the `OTAu Developer` title would encourage people to submit PRs :)

**Comment by mzfr** [comment]
@Corb3nik Is this one fixed? Because you, reznok have the title of `OTAu Developer` on OTAu Leaderboard.

**Comment by Corb3nik** [comment]
Nope, not yet :)

I want to add an actual page with all of the titles available in OTAu. Not just the ones completed by other members

**Comment by Corb3nik** [comment]
People suggested that we should keep the titles hidden, to keep the mystery. Closing this
