### ISSUE TITLE
Providing hints/documentation to members for challenges

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-University#50]
Some members would like to have hints/documentation to guide them through OTAu challenges.

How would we present that information?

Ideas : 
- Linking writeups to similar challenges
- Linking blog posts/articles
- Unlocking a hint for any challenge after solving X challenges

By @pusher

**Comment by mzfr** [comment]
I think linking writeups to similar challenges might give up a lot(emphasis on might), plus chances are there that other write-ups might not give the concept and only the `way` to solve it.

Linking blog posts/article could be a great way. And the 3rd point is also very legit this but again we need to keep in mind some people(like me :smiley: ) have a tough time solving simple problems.

Maybe doing both 2nd and 3rd might be a good idea. Like, don't give increment in hint count if the solved challenge had any connection to articles/post.

**Comment by Corb3nik** [comment]
After further discussion in Slack, we will go with the following : 

- No hint system
- The challenge author decides what hints to provide in the challenge description/title
- Further help can be requested through Slack

Advantages : 
- Members are forced to "try harder" on challenges, encouraging people to do their own research and learn.
- Forces people to talk on slack 😈

Disadvantages : 
- The learning curve is harder for new players, since their are no hints to help them get their first flags.

To solve this disadvantage, we should try to create specific beginner friendly tracks such as ROP 101, which is meant to teach new players specific concepts.
