### ISSUE TITLE
Scores converging to 50

### ISSUE THREAD

**Issue by gellyfisher** [OpenToAllCTF/OTA-University#86]
> the problem is during an infinite time challenge board all challenges could possibly reduce to 50 points

If more people join OTA university, even the hard challenges will be 50 points, so we need to have a bit more dynamics in our scoring. One suggestion that I have is to make the scoring dependant on the total amount of people.

**Comment by gellyfisher** [comment]
Suggestion for new scoring system in https://docs.google.com/spreadsheets/d/1RfHwtXbnB9FWBl3FckZQ81lXotwzo5OqQqkE1EYUwss/edit#gid=0

**Comment by Corb3nik** [comment]
After further discussion, we're gonna go with @gellyfisher's implementation :)

**Comment by gellyfisher** [comment]
fixed with commit af12ef047c1e616d8fb3cbe4ea76035ef311891d
